### ISSUE TITLE
Bundler silently fails in case of an error

### ISSUE THREAD

**Issue by Kikimora** [mrgrain/cdk-esbuild#237]
Not sure what was the original rational behind [this particular](https://github.com/mrgrain/cdk-esbuild/blob/3543558bf38e8b0ec54b39cb4cd8ffcc544c2f8f/src/bundler.ts#L208) `try...catch` block but it cased me a good bit of a headache today. In my case the build silently failed without producing any assets and CDK complained "Bundling did not produce any output". `buildSync` could not load `esbuild-darwin-arm64` (I'm on M1 Mac) and the `try...catch` block ate the error without giving a notice.

Here is the problematic block of code.
```ts
        try {
          const buildFn = this.props.buildFn ?? EsbuildProvider.require(props.esbuildModulePath).buildSync;
          const buildSync = EsbuildProvider.withEsbuildBinaryPath(buildFn, this.props.esbuildBinaryPath);

          buildSync({
            entryPoints,
            color: process.env.NO_COLOR ? Boolean(process.env.NO_COLOR) : undefined,
            ...(this.props?.buildOptions || {}),
            ...this.getOutputOptions(outputDir, { normalize, join }),
          });
        } catch (error) {
          if (errorHasCode(error, 'MODULE_NOT_FOUND')) {
            throw error;
          }
        }
```

**Comment by mrgrain** [comment]
Hi and thanks for reporting this!

Looking back at the history, this PR and the linked issue are the background to the current implementation.

https://github.com/mrgrain/cdk-esbuild/pull/212

I guess I later added a special case to handle Module Not Found errors, likely because of a similar issue you encountered.

---

Looking at the code now, I reckon we can move the first two lines out of the `try...catch` block. That should keep all important errors and stop any esbuild ones. 🤔

**Comment by mrgrain** [comment]
Hi and thanks for reporting this!

Looking back at the history, this PR and the linked issue are the background to the current implementation.

https://github.com/mrgrain/cdk-esbuild/pull/212

I guess, later on I added a special case to handle `Module Not Found` errors, likely because of a similar issue you encountered.

---

Looking at the code now, I reckon we can move the first two lines out of the `try...catch` block. That should keep all important errors and stop any esbuild ones. 🤔

**Comment by mrgrain** [comment]
It's also tracked as breaking change for the next major version, see #202

Not sure I still agree with my past self here. 😅
